apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config-fine
  namespace: kube-system
data:
  tesla-t4: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 10