apiVersion: v1
kind: ConfigMap
metadata:
 name: adapter-config
 namespace: monitoring
data:
 triton-adapter-config.yml: |
   rules:
   - seriesQuery: 'nv_inference_queue_duration_us{namespace="default",pod!=""}'
     resources:
       overrides:
         namespace: {resource: "namespace"}
         pod: {resource: "pod"}
     name:
       matches: "nv_inference_queue_duration_us"
       as: "avg_time_queue_us"
     metricsQuery: 'avg(delta(nv_inference_queue_duration_us{<<.LabelMatchers>>}[30s])/(1+delta(nv_inference_request_success{<<.LabelMatchers>>}[30s]))) by (<<.GroupBy>>)'