apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tritonserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tritonserver
  minReplicas: 1
  maxReplicas: 7
  metrics:
  - type: Pods
    pods:
      metric:
        name: avg_time_queue_us
      target:
        type: AverageValue
        averageValue: 50